### ISSUE TITLE
[bug] Files in S3 are missing the jpg/png extension after transferring from GCS

### ISSUE THREAD

**Issue by mrnewguy** [skyplane-project/skyplane#648]
**Describe the bug**
I used skyplane to cp a few GBs of jpg/png files from GCS to S3. Unfortunately, the files in s3 are now missing the jpg/png extension. 

**To Reproduce**
1. Run ```skyplane cp gs://BUCKET_NAME s3://BUCKET_NAME --recursive```

**Expected behavior**
The images that are in the S3 bucket should have the jpg/png extension too.  

**Screenshots**
![photo_2022-11-01_00-17-03](https://user-images.githubusercontent.com/38744968/199057124-a872d65b-0a16-4084-954a-ae296e169c13.jpg)

**Transfer client log**
![Screenshot from 2022-11-01 00-19-41](https://user-images.githubusercontent.com/38744968/199057649-5226302d-d6d0-4eea-934d-ee0d238bc7d3.png)

**Environment info (please complete the following information):**
 - OS: Linux 22.04
- Python 3.10.6

**Comment by parasj** [comment]
@mrnewguy Hi Ye, can you please share a screenshot of the GCP console for the bucket? It seems like the source paths do not have the JPG extension at the source.

<img width="502" alt="Screenshot 2022-10-31 at 10 13 43 AM" src="https://user-images.githubusercontent.com/453850/199089800-c5a916a3-9499-4b89-8f41-aade02bae23d.png">

**Comment by parasj** [comment]
@mrnewguy I've debugged this and can confirm MIME types are copied for transfers now for GCP and AWS. It was a bit tricky since list_object doesn't return a MIME type, so I lazily query it from the gateways. The PR should merge once CI passes: https://github.com/skyplane-project/skyplane/pull/655

Can you please test installing Skyplane from source? There will be a few more steps since you'll have to rebuild the gateway Docker container. https://skyplane.org/en/latest/build_from_source.html
